#!/usr/bin/env bash
echo "<!DOCTYPE html>"
echo "<html>"
echo "    <head>"
echo "        <title>Example</title>"
echo "    </head>"
echo "    <body>"
echo "        <H1>Hello from JB!</H1>"
echo "    </body>"
echo "</html>"
